GET http://localhost:8080/figurinhas

###

GET http://localhost:8080/figurinhas/obtidas

###

GET http://localhost:8080/figurinhas/faltantes

###

PATCH http://localhost:8080/figurinhas/BRA1

###

GET http://localhost:8080/figurinhas/BRA1

###

GET http://localhost:8080/figurinhas/FWC10

###

GET http://localhost:8080/figurinhas/CC14

###

GET http://localhost:8080/figurinhas/XYZ999

###

GET http://localhost:8080/figurinhas/secao/Brasil

###

GET http://localhost:8080/figurinhas/secao/Argentina

###

GET http://localhost:8080/figurinhas/secao/FIFA

###

GET http://localhost:8080/figurinhas/XYZ999