spring.application.name=completa-album

spring.datasource.url=jdbc:postgresql://localhost:5432/completa_album
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false